/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.guap.m721;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {

    }
}
