## default connection pool
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_m721
    username: m721_admin
    password=: ies4Aezire1thoi3
  jpa:
    hibernate:
      ddl-auto: validate