spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_m721
    username: m721_admin
    password=: ies4Aezire1thoi3
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql.BasicBinder: TRACE